### ISSUE TITLE
/mars size

### ISSUE THREAD

**Issue by haralambop** [schoebel/mars#12]
Hi Thomas,

Is there any mathematical function available to calculate the size of the /mars parttion

like size of mars_partition=f(number of files, size of the replicated partition,MB changes per min. etc etc)

thanks

andreas

**Comment by schoebel** [comment]
There is an internal scientific-style paper written by me for 1&1,
several years old, and in German. With lots of mathematical formulas.

It is about dimensioning of replication networks between data centers.
Dimensioning of /mars is only a sub-issue.

Once I will have some time, I will translate it to English and add it to
mars-manual.

For now, here is a simple general advice: measure your average write
rate. A good method is log-rotate every 10 minutes, and look at the size
of the _last_ transaction logfile shortly before the rotate. Of course,
you may also use "sar" statistics if you are aware that all data is
written twice (once to the transaction log, and another time to the
underlying disk via writeback in background).

These numbers must then be extrapolated to daily write traffic.

Hint: it does not depend on the size of your data partition. In no way.

There are exceptional 1&1 examples (e.g. databases) where /mars is
bigger than /dev/lv/mydata (the latter only a few gigabytes). And there
are other counter-examples where /mars is only a small fraction of
multi-dozen-terabyte data partitions.

Just measure your write rate, it does not depend on anything else.

Cheers,

Thomas

**Comment by astinf** [comment]
you can upload to git also in German

Ich kann auch Deutsch lesen .

Vielen dank im voraus :)

**Comment by schoebel** [comment]
I know, but the original paper had been marked "internal" long ago. I
would need an extra permission for overriding this. In contrast, if I
just write a new chapter as part of the MARS project, permission is
already granted by our CEO.

In addition, the new English version will not just form a plain
translation, but a _revised_ version (augmented with some newer
experiences).

Please be patient and give me some time to work on it :)

I will support the community as best as I can. It would go faster if one
day would have more than 24 h ;)

**Comment by schoebel** [comment]
Hope I close this very old issue. The new mars-user-manual.pdf has some guidance about this.
