### ISSUE TITLE
CURRENT_TIME macro replaced with current_time() API

### ISSUE THREAD

**Issue by sempervictus** [schoebel/mars#18]
There are a few places in the kernel module source where CURRENT_TIME macros are used:
```
brick_mem.c
brick_say.c
lamport.c
mars_copy.c
sy_old/mars_main.c
sy_old/mars_proc.c
```
In 4.14 (LTS) this is no longer available having been replaced with the current_time() API. Calling convention is a bit different, probably merits a look from developers since everyone will be running into this, and some version-magic ifdef-ing might be required.

**Comment by schoebel** [comment]
Thanks for the hint!

I had not yet time to look at the porting issues.

I think a small wrapper in lamport.h should solve the portability problem once in a single place.

I would be glad if you (or somebody else) could help me by sending patches (adapting to any kernel version) which also works for later kernels than 4.6.

My current plans: I _hope_ to be able to look into portability at May / June this year. At the moment, I am extremely focussed at Football (see the new sister repo of MARS, also included as a submodule) which will hopefully get a major "git push" in the next weeks, and it also deserves some documentation to be really useful for a broader audience. Afterwards I will have to look into some internal 1&1 kernel porting stuff. Probably some performance inprovements for extremely high IOPS demands (widening some SMP bottlenecks etc) could also be requested from me during the next months (e.g. some people from Strato have indicated some requirements in this direction).

So I am not sure about the priorities for the next few months, and thus any help from the community would be highly appreciated.

**Comment by sempervictus** [comment]
Copy that, will see if I can sneak a wrapper into the header to deal with this.

**Comment by schoebel** [comment]
Should have been fixed some time ago. Currently, kernels up to 4.14 are supported.
