### ISSUE TITLE
Write performance on /dev/mars/xxx

### ISSUE THREAD

**Issue by marvineq** [schoebel/mars#19]
Dear Thomas. First of all tanks for this great project. Great idea, stable and easy to use. 
I'm already running  2 instances with srcversion (mars0.1stable51) DC978237D6A5FCD5DA1C3AA on kernel  3.16.51. Both of them use 4xSSD RAID10 for  /mars folder. Performance is somehow good. Now I've  tried to run /mars on  two RAID1 SATA  and get write performance only about 20-30MB/s. Even when  moved /mars to RAID10 10xSATA (shared with LV that is used as underlying blockdevice for mars resource) there is no change in  write perfomance. Performance of lower layers (raid, lvm ) is ~ 10x better.  Tested on 2 different boxes, HW/SW raid..   Any idea what to check ?
Thanks , Vaclav

**Comment by marvineq** [comment]
Thanks for super fast answer. I'm aware of sw raid not recommended and BBU need  as you mentioned it  in documentation. Tested on AVAGO 3108 MegaRAID 2G cache. I will try benchmarks on different mars versions and let you know.

**Comment by schoebel** [comment]
Hope I can close this conversation. In the meantime, some effort has been invested into IO performance. Scalablity in number of secources is in RC stage, which will also greatly scale IO performance on SMP systems.
