### ISSUE TITLE
Consider /etc/hosts when resolving peer addresses

### ISSUE THREAD

**Issue by fgbreel** [schoebel/mars#27]
Hi @schoebel, I hope you are doing well,

I just got your email referencing the Debian's intent to package bug, thanks for the update!

I have a branch locally where I'm trying to have a place to run the test suite and I started with two virtual machines mimicking some hosts like so:

```
init_test_hostname() {
       sudo echo "192.168.33.10 istore-test-bs7" >> /etc/hosts
       sudo echo "192.168.33.20 istore-test-bap7" >> /etc/hosts
}
```

but found that the `marsadm` userspace tool uses `/usr/bin/host` which doesn't take in consideration the `/etc/hosts` file.

I have been using `/usr/bin/getent hosts $peer` instead. I think I need to skip addresses matching the `127.0.0.0/8` range too. (at 
https://github.com/schoebel/mars/blob/master/userspace/marsadm#L4122)

This something in my mind that I have to cleanup into a proper patch under `debian/patch` (plus `mars-Kconfig` and `mars-Makefile`), but if you can go ahead and change that in the next releases will be great help.

Regards,
Gabriel

**Comment by schoebel** [comment]
Hi Gabriel, I just fetched your 2 repos, and found no patch for marsadm.

So I just pushed WIP-getent . Please tell me if it fits your needs.

**Comment by fgbreel** [comment]
Hi @schoebel, thanks for your patience and sorry for my late reply,

I see it is already included on `mars0.1astable124` and it works!
Thanks for that, now I will try to have the test suite running.

Best
Gabriel Francisco
