### ISSUE TITLE
msghdr ctl_table issues Compiling for 4.0.5

### ISSUE THREAD

**Issue by grpomega** [schoebel/mars#8]
compiling under 4.0.5 gives the following errors in mars_net.c

block/mars/kernel/mars_net.c: In function '_mars_send_raw':
block/mars/kernel/mars_net.c:416:5: error: unknown field 'msg_iov' specified in initializer
     .msg_iov = (struct iovec*)&iov,
     ^
block/mars/kernel/mars_net.c: In function 'mars_recv_raw':
block/mars/kernel/mars_net.c:585:4: error: unknown field 'msg_iovlen' specified in initializer
    .msg_iovlen = 1,
    ^
block/mars/kernel/mars_net.c:585:18: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
    .msg_iovlen = 1,
                  ^
block/mars/kernel/mars_net.c:585:18: note: (near initialization for 'msg.msg_name')
block/mars/kernel/mars_net.c:586:4: error: unknown field 'msg_iov' specified in initializer
    .msg_iov = (struct iovec*)&iov,

Preprocessor output shows the msghdr from linux/socket.h
# 47 "include/linux/socket.h"
struct msghdr {
 void *msg_name;
 int msg_namelen;
 struct iov_iter msg_iter;
 void *msg_control;
 __kernel_size_t msg_controllen;
 unsigned int msg_flags;
};

If I explicitly define a renamed type eg mars_msghdr; compilation is fine; but this hack is not a solution.
I get the same with  ctl_table structure in sy_old/mars_proc.c

compilation line
 gcc -Wp,-MD,block/mars/kernel/.mars_net.o.d  \
-nostdinc \
-isystem /usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include \
-I./arch/x86/include -Iarch/x86/include/generated/uapi \
-Iarch/x86/include/generated  \
-Iinclude \
-I./arch/x86/include/uapi \
-Iarch/x86/include/generated/uapi \
-I./include/uapi \
-Iinclude/generated/uapi \
-include ./include/linux/kconfig.h \
-D__KERNEL__ \
-Wall -Wundef -Wstrict-prototypes \
-Wno-trigraphs \
-fno-strict-aliasing \
-fno-common \
-Werror-implicit-function-declaration \
-Wno-format-security -std=gnu89 \
-m64 \
-mno-80387 \
-mno-fp-ret-in-387 \
-mtune=generic \
-mno-red-zone \
-mcmodel=kernel \
-funit-at-a-time \
-maccumulate-outgoing-args \
-DCONFIG_AS_CFI=1 \
-DCONFIG_AS_CFI_SIGNAL_FRAME=1 \
-DCONFIG_AS_CFI_SECTIONS=1 \
-DCONFIG_AS_FXSAVEQ=1 \
-DCONFIG_AS_SSSE3=1 \
-DCONFIG_AS_CRC32=1 \
-DCONFIG_AS_AVX=1 \
-DCONFIG_AS_AVX2=1 \
-pipe \
-Wno-sign-compare \
-fno-asynchronous-unwind-tables \
-mno-sse \
-mno-mmx \
-mno-sse2 \
-mno-3dnow \
-mno-avx \
-fno-delete-null-pointer-checks \
-O2 --param=allow-store-data-races=0 \
-Wframe-larger-than=2048 \
-fstack-protector-strong \
-Wno-unused-but-set-variable \
-fno-omit-frame-pointer \
-fno-optimize-sibling-calls \
-fno-var-tracking-assignments \
-pg \
-mfentry \
-DCC_USING_FENTRY \
-Wdeclaration-after-statement \
-Wno-pointer-sign \
-fno-strict-overflow \
-fconserve-stack \
-Werror=implicit-int \
-Werror=strict-prototypes \
-Werror=date-time \
-DCC_HAVE_ASM_GOTO \
-fdelete-null-pointer-checks \
-fno-inline-functions \
-fno-inline-small-functions \
-fno-inline-functions-called-once  \
-DMODULE  \
-D"KBUILD_STR(s)=#s" \
-D"KBUILD_BASENAME=KBUILD_STR(mars_net)"  \
-D"KBUILD_MODNAME=KBUILD_STR(mars)" \
-c -o block/mars/kernel/.tmp_mars_net.o block/mars/kernel/mars_net.c

**Comment by schoebel** [comment]
Please look into the branch WIP-compatibility, where the problem should
be already fixed. Also, please read my message for you on github (answer
to your pull request).

Cheers,

Thomas

**Comment by grpomega** [comment]
Thanks for your directionI have downloaded the WIP_comaptibility branchIf I understandI do not need to include any of the kernel patches; other than the block/{Kconfig,Makefile} which trigger compilation.I am getting security_path_symlink undefinedWARNING: "security_path_symlink" [/usr/src/linux/block/mars/kernel/mars.ko] undefined!I have tried to include linux/security.h without successThank You in advanceOn Thursday, July 16, 2015 11:15 CDT, Thomas Schöbel-Theuer <notifications@github.com> wrote: Please look into the branch WIP-compatibility, where the problem shouldbe already fixed. Also, please read my message for you on github (answerto your pull request).Cheers,ThomasOn 07/16/2015 06:11 PM, grpomega wrote:> compiling under 4.!
 0.5 gives the following errors in mars_net.c>> block/mars/kernel/mars_net.c: In function '_mars_send_raw':> block/mars/kernel/mars_net.c:416:5: error: unknown field 'msg_iov' specified in initializer> .msg_iov = (struct iovec*)&iov,> ^> block/mars/kernel/mars_net.c: In function 'mars_recv_raw':> block/mars/kernel/mars_net.c:585:4: error: unknown field 'msg_iovlen' specified in initializer> .msg_iovlen = 1,> ^> block/mars/kernel/mars_net.c:585:18: warning: initialization makes pointer from integer without a cast [-Wint-conversion]> .msg_iovlen = 1,> ^> block/mars/kernel/mars_net.c:585:18: note: (near initialization for 'msg.msg_name')> block/mars/kernel/mars_net.c:586:4: error: unknown field 'msg_iov' specified in initializer> .msg_iov = (struct iovec*)&iov,>> Preproces!
 sor output shows the msghdr from linux/socket.h> # 47 "include/linux/socket.h"> struct msghdr {> void *msg_name;> int msg_namelen;> struct iov_iter msg_iter;> void *msg_control;> __kernel_size_t msg_controllen;> unsigned int msg_flags;> };>> If I explicitly define a renamed type eg mars_msghdr; compilation is fine; but this hack is not a solution.> I get the same with ctl_table structure in sy_old/mars_proc.c>> compilation line> gcc -Wp,-MD,block/mars/kernel/.mars_net.o.d \> -nostdinc \> -isystem /usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include \> -I./arch/x86/include -Iarch/x86/include/generated/uapi \> -Iarch/x86/include/generated \> -Iinclude \> -I./arch/x86/include/uapi \> -Iarch/x86/include/generated/uapi \> -I./include/uapi \> -Iinclude/generated/uapi \> -include ./include/linux/kconfig.h \> -D_!
 _KERNEL__ \> -Wall -Wundef -Wstrict-prototypes \> -Wno-trigraphs \> -fno-strict-aliasing \> -fno-common \> -Werror-implicit-function-declaration \> -Wno-format-security -std=gnu89 \> -m64 \> -mno-80387 \> -mno-fp-ret-in-387 \> -mtune=generic \> -mno-red-zone \> -mcmodel=kernel \> -funit-at-a-time \> -maccumulate-outgoing-args \> -DCONFIG_AS_CFI=1 \> -DCONFIG_AS_CFI_SIGNAL_FRAME=1 \> -DCONFIG_AS_CFI_SECTIONS=1 \> -DCONFIG_AS_FXSAVEQ=1 \> -DCONFIG_AS_SSSE3=1 \> -DCONFIG_AS_CRC32=1 \> -DCONFIG_AS_AVX=1 \> -DCONFIG_AS_AVX2=1 \> -pipe \> -Wno-sign-compare \> -fno-asynchronous-unwind-tables \> -mno-sse \> -mno-mmx \> -mno-sse2 \> -mno-3dnow \> -mno-avx \> -fno-delete-null-pointer-checks \> -O2 --p!
 aram=allow-store-data-races=0 \> -Wframe-larger-than=2048 \> -fstack-protector-strong \> -Wno-unused-but-set-variable \> -fno-omit-frame-pointer \> -fno-optimize-sibling-calls \> -fno-var-tracking-assignments \> -pg \> -mfentry \> -DCC_USING_FENTRY \> -Wdeclaration-after-statement \> -Wno-pointer-sign \> -fno-strict-overflow \> -fconserve-stack \> -Werror=implicit-int \> -Werror=strict-prototypes \> -Werror=date-time \> -DCC_HAVE_ASM_GOTO \> -fdelete-null-pointer-checks \> -fno-inline-functions \> -fno-inline-small-functions \> -fno-inline-functions-called-once \> -DMODULE \> -D"KBUILD_STR(s)=#s" \> -D"KBUILD_BASENAME=KBUILD_STR(mars_net)" \> -D"KBUILD_MODNAME=KBUILD_STR(mars)" \> -c -o block/mars/kernel/.tmp_mars_net.o block/mars/kernel/mars_net.c>>> ---> Reply to this email directly or view it on GitHub:> https://github.com/schoebel/mars/issues/8 —Reply to this email directly or view it on GitHub.

**Comment by schoebel** [comment]
I just pushed a forced update on WIP-compatibility which should fix this.
